Alen/mc gateway auth example
BuoyantIO/bel-examples pull request #66
Opened 2024-08-05 04:48 UTC by deusxanima

created initial bel-examples reference for configuring linkerd gw-mode multicluster with granular auth policies

2024-08-05 04:49 UTC, deusxanima commented
Once you approve, I'll clean up the merge conflicts and merge

2024-08-05 16:14 UTC, southsidedean commented on gitops/flux/helm-example/apps/linkerd-buoyant/helmrelease-linkerd-buoyant.yaml
Should the `linkerd-buoyant` version be `0.31.0`?  Isn't that the latest?

2024-08-05 16:15 UTC, southsidedean commented on gitops/terraform/environments/example/main.tf
> +  chart_version           = "2.15.4"
Should this be 2.15.5?

2024-08-05 17:26 UTC, southsidedean requested changes
Looks great, but there are a couple of versions I flagged that might need attention.  Please check those before you merge.

2024-08-12 14:55 UTC, deusxanima reviewed
fixed requested changes

2024-08-12 14:57 UTC, southsidedean approved these changes
Looks great!

2024-08-13 20:00 UTC, merged